Support for SAP annotations for OData v2
akorchev/odata2openapi pull request #34
Opened 2018-11-23 13:34 UTC by elsewhat

http://www.sap.com/Protocols/SAPData

SAP is using OData heavily for exposing APIs. For OData v2, SAP has provided their own extensions.
For OData v4 these extensions are mostly added to the Oasis standard.

Features support include:
-Detect SAP specific additions based on xmlNamespace
-Define operations based on EntitySet sap metadata (creatable, updatable etc)
-Include user friendly description pr property
-FunctionImport support
-List out expandable properties

In addition, added optional Options.schemes and Options.title properties.

2018-11-23 13:52 UTC, jhorbulyk commented
Are the SAP defnitions the same as the ones adapted in Odata v4 or are they different?

2018-11-23 14:29 UTC, elsewhat commented
For OData v2 SAP has provided an additional namespace xmlns:sap="http://www.sap.com/Protocols/SAPData"

Don't think there is a one-to-one match with changes in OData v4 possible.

There is a mapping from SAP showing the differences how various features in OData v2 is realized in OData v4 https://sapui5.hana.ondemand.com/1.36.6/docs/guide/341823349ed04df1813197f2a0d71db2.html

Tried to isolate so that the new logic only occurs if the namespace is provided, but was not always straightforward with out significant refactoring

2019-03-11 13:57 UTC, elsewhat commented
Any update on this pull request?

2019-03-11 14:46 UTC, jhorbulyk commented
@elsewhat Sorry.  I had forgotten about this.  I don't have an SAP instance which supports the above metadata formats so I can't test those directly but I suppose that I can make sure that the changes don't regress anyting and then publish a new version of the package.  Does that work for you?

2019-04-05 07:35 UTC, elsewhat commented
Works for me :)

2019-04-08 13:00 UTC, jhorbulyk commented
I just checked with my company's management about whether there is any requirement that you (@elsewhat ) need to sign a contributor license agreement (CLA).  They have told me that the answer to this question is yes.  However, unfortunately, they don't have such an agreement in place at this time but they are working to put this in place in the future.  This unfortunately means that I can't merge this PR at this time but I can come back to you once this infrastructure is put in place.

2019-08-09 17:41 UTC, snebjorn requested changes

2019-08-09 17:41 UTC, snebjorn commented on src/convert.ts
> +      operation['responses']['200']['schema']['properties']['d'] = operation['responses']['200']['schema']['properties']['value'];
In the SAP OData serivce I'm consuming the envelop is not using `value` but `results` see #44 
Not sure why.

Another "issue" is that this `d` won't have `type: 'object'` assigned, not sure what impact this has on the OpenApi spec

2019-08-09 17:43 UTC, snebjorn commented
@jhorbulyk what's the progress on this? I really could use this :)

2019-09-02 09:19 UTC, jhorbulyk commented
> @jhorbulyk what's the progress on this? I really could use this :)

@snebjorn Update is that I need @elsewhat to sign the cla.  @elsewhat are you willing to do this?

2019-09-10 08:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elasticio/odata2openapi?pullRequest=34) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elasticio/odata2openapi?pullRequest=34) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elasticio/odata2openapi?pullRequest=34) it.</sub>

2021-01-07 09:27 UTC, elsewhat commented
sorry, didn't catch the notification on this issue. 
Signed cla now

2021-03-23 10:58 UTC, nrdev88 commented
I could really use this. @elsewhat, could you please update the conflicts.

2021-03-23 11:50 UTC, elsewhat commented
@nrdev88 have resolved the conflicts, but not able to verify the functionality at the moment. Could you see if it fits your need ?

2023-10-23 14:00 UTC, closed without merging